var Nombres = ["RODRIGO","MIGUEL","LUCAS","MATIAS", "GASTON","FACUNDO","MARIANO",
               "FRANCISCO","MAXIMILIANO", "ALBERTO", "JUAN", "MANUEL", "NICOLAS",
               "MARIA", "ANALIA", "SANDRA", "GRACIELA", "MARIANA", "ANA", "SOLEDAD", "JUANA", "FATIMA"];

var Paises = ["ARGENTINA", "MEXICO", "BRASIL", "GUATEMALA", "ESPAÑA", "ITALIA",
    "ESTADOS UNIDOS", "BELGICA", "IRAN", "ISRAEL", "FRANCIA", "JAPON", "CHINA"];

var Continentes = ["AMERICA", "EUROPA", "ASIA", "AFRICA", "OCEANIA", "ANTARTIDA"];



