var Nombres = ["RODRIGO",
    "MIGUEL",
    "LUCAS",
    "MATIAS",
    "GASTON",
    "FACUNDO",
    "MARIANO",
    "FRANCISCO",
    "MAXIMILIANO", "ALBERTO", "JUAN", "MANUEL", "NICOLAS",
    "MARIA", "ANALIA", "SANDRA", "GRACIELA", "MARIANA", "ANA", "SOLEDAD", "JUANA", "FATIMA"
];

var Paises = ["ARGENTINA", "MEXICO", "BRASIL", "GUATEMALA", "ESPAÑA", "ITALIA",
    "ESTADOS UNIDOS", "BELGICA", "IRAN", "ISRAEL", "FRANCIA", "JAPON", "CHINA"
]

var Continentes = ["AMERICA", "EUROPA", "ASIA", "AFRICA", "OCEANIA", "ARTARTIDA"]



var Frases = ["BART NO QUIERO ASUSTARTE PERO TAL VEZ EL COCO, EL COCO ESTA EN LA CASA",
    "SOY INTELECTUAL, MUY INTELIGENTE, ¡AY QUE BONITO SOY!",
    "NORMALMENTE NO REZO, PERO SI ESTAS AHI, POR FAVOR, ¡SALVAME SUPERMAN!",
    "¿QUE TE PASO VIEJO? ANTES ERAS CHEVERE",
    "NO PUEDES ESCONDERTE DE MI, PASO VEINTITRES HORAS DIARIAS AQUI",
    "NO VIVES DE ENSALADA",
    "A LA GRANDE LE PUSE CUCA",
    "HE VISTO MUCHAS BASOFIAS, PERO ESTOS SON LA MAYOR BASOFIA ENTRE LAS BASOFIAS",
    "AY ESTA GRASA NO SE QUITA",
    "CREO QUE ODIO A MICHAEL JACKSON, NO LA VERDAD QUE CANTA BIEN Y ES NOBLE",
    "COMPRENLO MUCHACHOS, NO ME HICE RICO FIRMANDO CHEQUES",
    "ME QUIERO VOLVER CHANGO! MI AUTO!",
    "NANANANANANANANA ¡BATMAN!, DIGO ¡LIDER!",
    "COMPUTADORA MATA A FLANDERS",
    "ESCUELA DE PAYASOS, ESO NO SE COME",
    "SIEMPRE DUDE DE LA EXISTENCIA DE DIOS, AHORA SE QUE EXISTE... SOY YO",
    "ES MEJOR QUEDARSE CALLADO Y PASAR POR TONTO QUE ABRIR LA BOCA Y DESPEJAR LAS DUDAS",
    "SI YO ME MURIERA, REENCARNARIA EN MARIPOSA, NADIE SOSPECHARIA DE UNA MARIPOSA"
];